### ISSUE TITLE
weird case with nil channel

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/goprocess#10]
```
goroutine 22 [chan receive (nil chan)]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/context.func·001()
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/context/context.go:31 +0x65
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/context.WithContextAndTeardown
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/context/context.go:33 +0x172
```

**Comment by jbenet** [comment]
fixed in https://github.com/jbenet/goprocess/pull/11
