### ISSUE TITLE
panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by hsanjuan** [jbenet/goprocess#22]
I have recently started getting these occasionally. I have also recently updated deps so that I started using the `v0.1.2` tag.

@Stebalien I see you merged some recent fixes, might this be related? I never saw this panic before.

```
=== RUN   TestConsensusPin
panic: assignment to entry in nil map

goroutine 93 [running]:
github.com/jbenet/goprocess.(*process).AddChildNoWait(0xc000231a40, 0x113fbc0, 0xc0000b3e60)
        /home/hector/go/pkg/mod/github.com/jbenet/goprocess@v0.1.2/impl-mutex.go:72 +0x18d
github.com/jbenet/goprocess/context.WithProcessClosing(0x112eaa0, 0xc000218ac0, 0x113fbc0, 0xc000231a40, 0x0, 0x0)
        /home/hector/go/pkg/mod/github.com/jbenet/goprocess@v0.1.2/context/context.go:85 +0x170
github.com/jbenet/goprocess/context.OnClosingContext(...)
        /home/hector/go/pkg/mod/github.com/jbenet/goprocess@v0.1.2/context/derive.go:12
github.com/ipfs/go-bitswap.(*Bitswap).provideWorker(0xc0002ea500, 0x113fbc0, 0xc000231a40)
        /home/hector/go/pkg/mod/github.com/ipfs/go-bitswap@v0.0.5/workers.go:109 +0x6a
github.com/jbenet/goprocess.(*process).Go.func1(0xc0004ba600, 0xc000231a40, 0xc000231aa0)
        /home/hector/go/pkg/mod/github.com/jbenet/goprocess@v0.1.2/impl-mutex.go:112 +0x3c
created by github.com/jbenet/goprocess.(*process).Go
        /home/hector/go/pkg/mod/github.com/jbenet/goprocess@v0.1.2/impl-mutex.go:111 +0x1f7
```

**Comment by Stebalien** [comment]
Apparently, adding a child to a closed process is illegal and adding one to a closing process is buggy. I'm going to make that "just work".
